#include "plugins/limiter/Dsp.hpp"
#include <iostream>
#include <cstdlib>
using namespace just;using namespace just::limiter;
static unsigned checks=0;static void check(bool b,const char* why){++checks;if(!b){std::cerr<<"FAIL "<<why<<'\n';std::exit(1);}}
int main(){auto fresh=initialState({},registry);check(fresh.targets[algorithmVersion]==1,"new instances use version1");check(parameters[algorithmVersion].restoreMissingDefault==0&& !parameters[algorithmVersion].automatable,"approved missing restore and nonautomation");for(unsigned n:{9u,10u}){ParameterRegistry old{parameters,n};auto legacy=fresh;legacy.targets[mode]=1;legacy.targets[ceiling]=.71234;legacy.seed=12345;auto bytes=encodeState(legacy,old);SoundState restored;check(decodeState(bytes.data(),bytes.size(),{},registry,restored)==StateResult::ok,"old state decoded");check(restored.targets[algorithmVersion]==0,"old missing ID selects legacy");for(unsigned i=0;i<n;++i)check(restored.targets[i]==legacy.targets[i],"old targets preserved");check(restored.seed==12345,"seed preserved");auto saved=encodeState(restored,registry);SoundState again;check(decodeState(saved.data(),saved.size(),{},registry,again)==StateResult::ok&&again.targets[algorithmVersion]==0,"resave preserves explicit legacy");restored.targets[algorithmVersion]=1;saved=encodeState(restored,registry);check(decodeState(saved.data(),saved.size(),{},registry,again)==StateResult::ok&&again.targets[algorithmVersion]==1,"explicit upgraded state persists");for(unsigned i=0;i<n;++i)check(again.targets[i]==legacy.targets[i],"upgrade changes only version");}
 LimiterEngine e;check(e.prepare({48000,1,2,2}),"prepare router");auto s=fresh;s.targets[algorithmVersion]=0;e.applyTargets(s,0);double error=0;
 for(unsigned i=0;i<12000;++i){if(i==2500||i==2750||i==6000||i==8000){s.targets[algorithmVersion]=i==2500||i==6000?1:0;e.applyTargets(s,0);}double x=.2*std::sin(i*.17),right=-.6*x,a=0,b=0;AudioBlock<double> block{{&x,&right},{&a,&b},2,2,1};e.process(block,{});const double expected=i<e.latencySamples()?0:.2*std::sin((i-e.latencySamples())*.17);error=std::max(error,std::abs(a-expected));check(std::isfinite(a)&&std::isfinite(b),"finite during repeated/reversed version transition");}
 check(error<3e-15,"version transition preserves aligned untriggered Live audio without cold-buffer dip");check(e.latencySamples()==288,"version does not change PDC");std::cout<<"PASS "<<checks<<" algorithm migration and live version-switch checks; neutral transition null="<<error<<'\n';}
