#include "public.sdk/source/vst/hosting/module.h"
#include "public.sdk/source/vst/hosting/hostclasses.h"
#include "public.sdk/source/vst/hosting/parameterchanges.h"
#include "public.sdk/source/common/memorystream.h"
#include "pluginterfaces/vst/ivstaudioprocessor.h"
#include "pluginterfaces/vst/ivstprocesscontext.h"
#include <array>
#include <vector>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <filesystem>
#include <cmath>
#include <cstring>
#include <algorithm>
using namespace Steinberg;using namespace Steinberg::Vst;
using Bytes=std::vector<std::uint8_t>;using Stereo=std::array<std::vector<double>,2>;
static unsigned checks=0;static void require(bool b,const char* why){++checks;if(!b){std::cerr<<"FAIL "<<why<<'\n';std::exit(1);}}
static std::uint32_t integer(const Bytes& b,std::size_t at){require(at+4<=b.size(),"bounded state read");std::uint32_t v=0;for(unsigned k=0;k<4;++k)v|=std::uint32_t(b[at+k])<<(8*k);return v;}
static void putInteger(Bytes& b,std::size_t at,std::uint32_t v){for(unsigned k=0;k<4;++k)b[at+k]=std::uint8_t(v>>(8*k));}
static double target(const Bytes& b,unsigned id){require(integer(b,0)==0x3154534a,"state signature");auto count=integer(b,36);for(unsigned i=0;i<count;++i)if(integer(b,44+12*i)==id){double value;std::memcpy(&value,b.data()+48+12*i,8);return value;}return -999;}
static void set(Bytes& b,unsigned id,double value,bool append=false){auto count=integer(b,36);for(unsigned i=0;i<count;++i)if(integer(b,44+12*i)==id){std::memcpy(b.data()+48+12*i,&value,8);return;}require(append&&integer(b,40)==0,"append only explicitly approved parameter to config-free fixture");auto at=b.size();b.resize(at+12);putInteger(b,at,id);std::memcpy(b.data()+at+4,&value,8);putInteger(b,36,count+1);}
static Bytes read(const std::filesystem::path& p){std::ifstream f(p,std::ios::binary);require(bool(f),"read fixture");return {std::istreambuf_iterator<char>(f),{}};}
static void write(const std::filesystem::path& p,const Bytes& b){std::ofstream f(p,std::ios::binary);f.write((const char*)b.data(),b.size());require(bool(f),"write diagnostic fixture");}
static Stereo input(unsigned count=8192){Stereo s;for(auto&v:s)v.resize(count);for(unsigned i=0;i<count;++i){s[0][i]=i<count-300?(i%97==0?3.7:.67*std::sin(i*.13)+.31*std::cos(i*2.719)):0;s[1][i]=-.43*s[0][i]+(i<count-300?.11*std::sin(i*.91):0);}return s;}
struct Event{int sample;ParamID id;double normalized;};
struct Result{Stereo output;Bytes restored;unsigned latency=0;};
class Host {
 VST3::Hosting::Module::Ptr module;HostApplication app;
public:
 explicit Host(const char* path){std::string error;module=VST3::Hosting::Module::create(path,error);require(bool(module),error.c_str());}
 Bytes defaults(){auto infos=module->getFactory().classInfos();auto c=module->getFactory().createInstance<IComponent>(infos[0].ID());require(c&&c->initialize(&app)==kResultOk,"create component");MemoryStream m;require(c->getState(&m)==kResultOk,"actual getState");auto p=(const std::uint8_t*)m.getData();Bytes b(p,p+m.getSize());c->terminate();return b;}
 template<class T> Result render(const Bytes& state,const Stereo& input,double fs=48000,const std::vector<Event>& events={}){auto infos=module->getFactory().classInfos();auto c=module->getFactory().createInstance<IComponent>(infos[0].ID());require(c&&c->initialize(&app)==kResultOk,"create actual component");FUnknownPtr<IAudioProcessor> p(c);require(bool(p),"processor");Bytes copy=state;MemoryStream m(copy.data(),int64(copy.size()));require(c->setState(&m)==kResultOk,"restore isolated instance");SpeakerArrangement stereo=SpeakerArr::kStereo;require(p->setBusArrangements(&stereo,1,&stereo,1)==kResultOk,"stereo bus");constexpr int block=128;const int format=std::is_same_v<T,float>?kSample32:kSample64;ProcessSetup setup{kOffline,format,block,fs};require(p->setupProcessing(setup)==kResultOk,"prepare offline");require(c->setActive(true)==kResultOk,"activate component");auto processing=p->setProcessing(true);require(processing==kResultOk||processing==kNotImplemented,"SDK process notification");Result result;result.latency=p->getLatencySamples();const int count=int(input[0].size())+result.latency+100;for(auto&v:result.output)v.resize(count);std::array<T,block> l{},r{},a{},b{};T* ins[]={l.data(),r.data()};T* outs[]={a.data(),b.data()};
  for(int at=0;at<count;at+=block){const int n=std::min(block,count-at);for(int k=0;k<n;++k){l[k]=at+k<int(input[0].size())?T(input[0][at+k]):0;r[k]=at+k<int(input[1].size())?T(input[1][at+k]):0;}AudioBusBuffers in{},out{};in.numChannels=out.numChannels=2;if constexpr(std::is_same_v<T,float>){in.channelBuffers32=ins;out.channelBuffers32=outs;}else{in.channelBuffers64=ins;out.channelBuffers64=outs;}ProcessContext context{};context.state=ProcessContext::kPlaying;context.sampleRate=fs;context.projectTimeSamples=at;ProcessData data{};data.processMode=kOffline;data.symbolicSampleSize=format;data.numSamples=n;data.numInputs=data.numOutputs=1;data.inputs=&in;data.outputs=&out;data.processContext=&context;ParameterChanges changes(11);for(const auto& event:events)if(event.sample>=at&&event.sample<at+n){int32 queueIndex=0,pointIndex=0;auto queue=changes.addParameterData(event.id,queueIndex);require(queue&&queue->addPoint(event.sample-at,event.normalized,pointIndex)==kResultOk,"host parameter point");}data.inputParameterChanges=&changes;require(p->process(data)==kResultOk,"actual installed/candidate audio callback");for(int k=0;k<n;++k){require(std::isfinite(a[k])&&std::isfinite(b[k]),"finite actual audio");result.output[0][at+k]=a[k];result.output[1][at+k]=b[k];}}
  MemoryStream saved;require(c->getState(&saved)==kResultOk,"read back actual restored state");auto ptr=(std::uint8_t*)saved.getData();result.restored.assign(ptr,ptr+saved.getSize());p->setProcessing(false);c->setActive(false);c->terminate();return result;
 }
};
static Bytes audioBytes(const Result& r){Bytes b(r.output[0].size()*16);for(unsigned i=0;i<r.output[0].size();++i){std::memcpy(b.data()+i*16,&r.output[0][i],8);std::memcpy(b.data()+i*16+8,&r.output[1][i],8);}return b;}
static double null(const Stereo& input,const Result& result,double scalar=1){double error=0;for(unsigned ch=0;ch<2;++ch)for(unsigned i=0;i<input[ch].size();++i)error=std::max(error,std::abs(result.output[ch][i+result.latency]-input[ch][i]*scalar));return error;}
// Independent diagnostic reconstruction; no production DSP/header dependency.
static double independentPeak(const Stereo& input){constexpr unsigned radius=64,phases=64,taps=129;constexpr double pi=3.14159265358979323846;double peak=0;for(unsigned p=0;p<phases;++p){std::array<double,taps> h{};double sum=0;for(unsigned k=0;k<taps;++k){double d=int(k)-int(radius)-double(p)/phases;h[k]=std::abs(d)>=radius?0:(std::abs(d)<1e-12?1:std::sin(pi*d)/(pi*d))*(.42+.5*std::cos(pi*d/radius)+.08*std::cos(2*pi*d/radius));sum+=h[k];}for(auto&v:h)v/=sum;for(auto&channel:input)for(int n=0;n<int(channel.size());++n){double y=0;for(unsigned k=0;k<taps;++k){int at=n-int(radius)+int(k);if(at>=0&&at<int(channel.size()))y+=h[k]*channel[at];}peak=std::max(peak,std::abs(y));}}return peak;}
template<class T> static void actualNewAudio(Host& host,const Bytes& defaults,const std::filesystem::path& evidence){
 for(double fs:{44100.,48000.,96000.})for(unsigned mode=0;mode<2;++mode){Stereo signal=input(4096);for(auto&ch:signal)for(auto&v:ch)v=double(T(v*.025));auto state=defaults;set(state,7,mode);auto result=host.render<T>(state,signal,fs);require(result.latency==unsigned(std::ceil(fs*.005))+48,"actual rate-dependent unchanged PDC");double error=null(signal,result);require(error==0,"float32/64 neutral candidate exact null");std::cout<<"RATE_NULL bits="<<sizeof(T)*8<<" mode="<<mode<<" fs="<<fs<<" error="<<error<<" pdc="<<result.latency<<'\n';}
 for(unsigned probe=0;probe<6;++probe){Stereo signal;for(auto&ch:signal)ch.resize(probe==5?36000:4096);for(unsigned i=0;i<signal[0].size();++i){double x=0;if(probe==0)x=i%4<2?.99:-.99;if(probe==1)x=i==1024?2.:i==1088?-3.:0;if(probe==2)x=1.2*std::sin(2*3.14159265358979323846*23500*i/48000+3.14159265358979323846/4);if(probe==3)x=.85*std::sin(i*.512)+.65*std::cos(i*1.853)+.55*std::sin(i*i*.1426);if(probe==4)x=i==1024?4.:.01*std::sin(i*.7);if(probe==5)x=i>=2048&&i<4096?2.5*std::sin(i*1.7):.1*std::sin(i*.31);signal[0][i]=double(T(x));signal[1][i]=double(T(-.4*x));}auto state=defaults;set(state,7,1);auto result=host.render<T>(state,signal);write(evidence/("tp-bits"+std::to_string(sizeof(T)*8)+"-probe"+std::to_string(probe)+".f64"),audioBytes(result));double peak=independentPeak(result.output);require(peak<=1+1e-7,"actual candidate 64x129 selected TP boundaries");std::cout<<"ACTUAL_TP bits="<<sizeof(T)*8<<" probe="<<probe<<" independent64x129="<<peak<<'\n';}
 Stereo quiet;for(auto&ch:quiet)ch.assign(8192,.5);for(unsigned mode=0;mode<2;++mode){auto state=defaults;set(state,7,mode);set(state,0,1);auto result=host.render<T>(state,quiet,48000,{{4000,0,0}});for(unsigned i=3500;i<5000;++i)require(std::abs(result.output[0][i]-.5)<(sizeof(T)==4?6e-8:3e-15),"actual low-level bypass re-entry has no dip");std::cout<<"BYPASS_REENTRY bits="<<sizeof(T)*8<<" mode="<<mode<<" below_ceiling_dip=0\n";}
}
int main(int argc,char**argv){require(argc==5,"usage: bundle capture-old|verify-new baseline-fixture-directory evidence-directory");const std::string action=argv[2];const std::filesystem::path baseline=argv[3],evidence=argv[4];std::filesystem::create_directories(evidence);Host host(argv[1]);auto defaults=host.defaults();write(evidence/"loaded-default.state",defaults);std::cout<<std::setprecision(17);const auto signal=input();
 if(action=="capture-old"){require(target(defaults,10)==-999,"capture must use genuine pre-version 7d bundle");std::filesystem::create_directories(baseline);for(unsigned mode=0;mode<2;++mode){auto state=defaults;set(state,1,27./60);set(state,2,21.3/24);set(state,3,std::log(137./10)/std::log(200));set(state,4,.8231884765625);set(state,5,.64);set(state,6,21./24);set(state,7,mode);set(state,9,30./36);const auto result=host.render<double>(state,signal);require(result.latency==288,"baseline PDC");const auto stem="legacy7d-"+std::to_string(mode);write(baseline/(stem+".state"),state);write(baseline/(stem+".f64"),audioBytes(result));std::cout<<"CAPTURE "<<stem<<" state_param_count="<<integer(state,36)<<" stereo_frames="<<result.output[0].size()<<" pdc="<<result.latency<<'\n';}}
 else if(action=="verify-new"){require(target(defaults,10)==1,"new actual bundle defaults to transparent version1");for(unsigned mode=0;mode<2;++mode){const auto stem="legacy7d-"+std::to_string(mode);auto state=read(baseline/(stem+".state"));auto result=host.render<double>(state,signal);require(target(result.restored,10)==0,"old10-ID state selects compatibility version0");for(unsigned id=0;id<10;++id)require(target(state,id)==target(result.restored,id),"all old parameter targets retained exactly");require(audioBytes(result)==read(baseline/(stem+".f64")),"old7d full audio bit exact through candidate bundle");std::cout<<"LEGACY "<<mode<<" bit_exact=1 pdc="<<result.latency<<'\n';auto upgraded=state;set(upgraded,10,1,true);auto changed=host.render<double>(upgraded,signal);require(target(changed.restored,10)==1,"explicit upgrade remains version1");for(unsigned id=0;id<10;++id)require(target(state,id)==target(changed.restored,id),"upgrade changes only appended algorithm version");}
  Stereo quiet=input(4096);for(unsigned ch=0;ch<2;++ch)for(auto&v:quiet[ch])v*=.05;for(unsigned mode=0;mode<2;++mode){auto state=defaults;set(state,7,mode);auto result=host.render<double>(state,quiet);const double error=null(quiet,result);require(error<3e-15,"actual new bundle neutral low-level null");std::cout<<"NULL mode="<<mode<<" peak="<<error<<" pdc="<<result.latency<<'\n';auto outState=state;set(outState,9,24./36);auto post=host.render<double>(outState,quiet);require(null(quiet,post,std::pow(10.,-12./20))<3e-15,"actual independent post gain");}
  actualNewAudio<float>(host,defaults,evidence);actualNewAudio<double>(host,defaults,evidence);
 }else require(false,"explicit diagnostic action");std::cout<<"PASS "<<checks<<" loaded-bundle checks; no controller/view/window/audio device; no user project edits\n";
}
