#include "plugins/limiter/TransparentDsp.hpp"
#include <cstdlib>
#include <iostream>
#include <chrono>
static thread_local bool inAudio=false;static unsigned allocations=0,releases=0,checks=0;
void* operator new(std::size_t n){if(inAudio)++allocations;if(auto p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void* operator new[](std::size_t n){return ::operator new(n);}
void operator delete(void* p)noexcept{if(inAudio&&p)++releases;std::free(p);}void operator delete[](void* p)noexcept{::operator delete(p);}void operator delete(void* p,std::size_t)noexcept{::operator delete(p);}void operator delete[](void* p,std::size_t)noexcept{::operator delete(p);}
using namespace just;using namespace just::limiter;
static void check(bool b,const char* s){++checks;if(!b){std::cerr<<"FAIL "<<s<<'\n';std::exit(1);}}
static void set(SoundState& s,unsigned id,double x){s.targets[id]=parameters[id].toNormalized(x);}
template<class T> static void run(bool tp){constexpr unsigned block=128,blocks=750;TransparentLimiterEngine a,b;PrepareSpec spec{48000,block,2,2,0,std::is_same_v<T,float>?SampleFormat::float32:SampleFormat::float64};check(a.prepare(spec)&&b.prepare(spec),"prepare");auto sa=initialState({},registry),sb=sa;set(sa,mode,tp);set(sb,mode,tp);set(sa,input,6);set(sb,input,6);set(sb,output,-12);a.applyTargets(sa,0);b.applyTargets(sb,0);std::array<T,block>l{},r{},oa{},ob{},oc{},od{};double largestScalar=0,maxReductionDifference=0;const double scalar=std::pow(10.,-12./20);auto start=std::chrono::steady_clock::now();for(unsigned n=0;n<blocks;++n){if(n==100||n==200){set(sa,bypass,n==100?1:0);set(sb,bypass,n==100?1:0);}if(n==300){set(sa,ceiling,-3);set(sb,ceiling,-3);}if(n==400){set(sa,lookahead,5);set(sb,lookahead,5);}for(unsigned i=0;i<block;++i){auto j=n*block+i;l[i]=T(.9*std::sin(j*.19)+.4*std::cos(j*.87));r[i]=T(.05*std::sin(j*1.17));}AudioBlock<T> ba{{l.data(),r.data()},{oa.data(),ob.data()},2,2,block},bb{{l.data(),r.data()},{oc.data(),od.data()},2,2,block};inAudio=true;a.applyTargets(sa,0);b.applyTargets(sb,0);a.process(ba,{});b.process(bb,{});a.endBlock();b.endBlock();inAudio=false;MeterSnapshot ma,mb;check(a.readMeter(ma)&&b.readMeter(mb),"read meters");maxReductionDifference=std::max(maxReductionDifference,std::abs(ma.maxGainReductionDb-mb.maxGainReductionDb));for(unsigned i=0;i<block;++i){check(std::isfinite(oa[i])&&std::isfinite(oc[i]),"finite actual processing");if(n<100||n>202)largestScalar=std::max(largestScalar,std::abs(double(oc[i])-double(oa[i])*scalar));if(n>=110&&n<200){check(oa[i]==oc[i],"stable bypass ignores Output");}}}auto seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();check(maxReductionDifference==0,"Output never affects control GR, including bypass re-entry");check(largestScalar<(std::is_same_v<T,float>?6e-8:2e-15),"independent settled Output scalar");check(!allocations&&!releases,"no new/delete during process, target changes or endBlock");std::cout<<"RT sample_bits="<<sizeof(T)*8<<" TP="<<tp<<" null_scalar="<<largestScalar<<" GR_diff="<<maxReductionDifference<<" allocations="<<allocations<<" releases="<<releases<<" two_engine_seconds="<<seconds<<" audio_seconds="<<double(block*blocks)/48000<<'\n';}
int main(){for(bool tp:{false,true}){run<float>(tp);run<double>(tp);}std::cout<<"PASS "<<checks<<" RT/output/bypass/finite checks; wall time is diagnostic, not a host deadline certification\n";}
