#pragma once
#include "common/state/State.hpp"
namespace just::reverb {
enum ID : ParamID {
    Bypass = 0,
    Decay = 100,
    Predelay = 101,
    HighCut = 102,
    Mix = 103,
    Style = 110,
    Size = 111,
    EarlyLate = 112,
    Diffusion = 113,
    LowDecay = 120,
    MidDecay = 121,
    HighDecay = 122,
    LowXover = 123,
    HighXover = 124,
    ModRate = 130,
    ModDepth = 131,
    WetHP = 140,
    Bell1Freq = 141,
    Bell1Gain = 142,
    Bell1Q = 143,
    Bell1On = 144,
    Bell2Freq = 145,
    Bell2Gain = 146,
    Bell2Q = 147,
    Bell2On = 148,
    Width = 150,
    WetLevel = 151,
    InputTrim = 152,
    OutputTrim = 153,
    DuckAmount = 160,
    DuckThreshold = 161,
    DuckAttack = 162,
    DuckRelease = 163,
    Freeze = 170,
    Sync = 180,
    Division = 181,
};
inline constexpr const char* styleLabels[]={"Room","Hall","Plate"};
inline constexpr const char* divisionLabels[]={"1/32","1/32 T","1/32 D","1/16","1/16 T","1/16 D","1/8","1/8 T","1/8 D","1/4","1/4 T","1/4 D"};
inline constexpr double divisionBeats[]={.125,1./12.,.1875,.25,1./6.,.375,.5,1./3.,.75,1.,2./3.,1.5};
inline constexpr ParameterSpec parameters[]={
    {"reverb.bypass",Bypass,"Bypass","",0,1,0,Mapping::linear,1,true,"all",Transition::discrete,10},
    {"reverb.decay",Decay,"Decay","s",0.1,20,1.2,Mapping::logarithmic,0,true,"all",Transition::continuous,50},
    {"reverb.predelay_ms",Predelay,"Pre-delay","ms",0,500,20,Mapping::linear,0,true,"all",Transition::continuous,20},
    {"reverb.wet_lp_hz",HighCut,"High Cut","Hz",1000,20000,12000,Mapping::logarithmic,0,true,"all",Transition::continuous,20},
    {"reverb.mix",Mix,"Mix","%",0,100,20,Mapping::linear,0,true,"all",Transition::continuous,10},
    {"reverb.style",Style,"Style","",0,2,0,Mapping::linear,2,true,"all",Transition::discrete,100,styleLabels},
    {"reverb.size",Size,"Size","%",25,200,100,Mapping::logarithmic,0,true,"all",Transition::continuous,100},
    {"reverb.early_late",EarlyLate,"Late Balance","%",0,100,65,Mapping::linear,0,true,"all",Transition::continuous,20},
    {"reverb.diffusion",Diffusion,"Diffusion","%",0,100,70,Mapping::linear,0,true,"all",Transition::continuous,20},
    {"reverb.low_decay",LowDecay,"Low Decay","x",0.25,2,1,Mapping::logarithmic,0,true,"all",Transition::continuous,50},
    {"reverb.mid_decay",MidDecay,"Mid Decay","x",0.25,2,1,Mapping::logarithmic,0,true,"all",Transition::continuous,50},
    {"reverb.high_decay",HighDecay,"High Decay","x",0.25,2,0.65,Mapping::logarithmic,0,true,"all",Transition::continuous,50},
    {"reverb.low_crossover_hz",LowXover,"Low Crossover","Hz",80,1000,250,Mapping::logarithmic,0,true,"all",Transition::continuous,20},
    {"reverb.high_crossover_hz",HighXover,"High Crossover","Hz",1000,12000,4000,Mapping::logarithmic,0,true,"all",Transition::continuous,20},
    {"reverb.mod_rate_hz",ModRate,"Mod Rate","Hz",0.05,2,0.3,Mapping::logarithmic,0,true,"all",Transition::continuous,50},
    {"reverb.mod_depth_ms",ModDepth,"Mod Depth","ms",0,2,0.2,Mapping::linear,0,true,"all",Transition::continuous,50},
    {"reverb.wet_hp_hz",WetHP,"Wet HP","Hz",20,2000,80,Mapping::logarithmic,0,true,"all",Transition::continuous,20},
    {"reverb.bell1_hz",Bell1Freq,"Bell 1 Freq","Hz",20,20000,500,Mapping::logarithmic,0,true,"all",Transition::continuous,20},
    {"reverb.bell1_gain_db",Bell1Gain,"Bell 1 Gain","dB",-12,12,0,Mapping::linear,0,true,"all",Transition::continuous,20},
    {"reverb.bell1_q",Bell1Q,"Bell 1 Q","",0.2,8,1,Mapping::logarithmic,0,true,"all",Transition::continuous,20},
    {"reverb.bell1_enabled",Bell1On,"Bell 1 Enabled","",0,1,0,Mapping::linear,1,true,"all",Transition::discrete,10},
    {"reverb.bell2_hz",Bell2Freq,"Bell 2 Freq","Hz",20,20000,4000,Mapping::logarithmic,0,true,"all",Transition::continuous,20},
    {"reverb.bell2_gain_db",Bell2Gain,"Bell 2 Gain","dB",-12,12,0,Mapping::linear,0,true,"all",Transition::continuous,20},
    {"reverb.bell2_q",Bell2Q,"Bell 2 Q","",0.2,8,1,Mapping::logarithmic,0,true,"all",Transition::continuous,20},
    {"reverb.bell2_enabled",Bell2On,"Bell 2 Enabled","",0,1,0,Mapping::linear,1,true,"all",Transition::discrete,10},
    {"reverb.width",Width,"Width","%",0,150,100,Mapping::linear,0,true,"all",Transition::continuous,20},
    {"reverb.wet_level_db",WetLevel,"Wet Level","dB",-90,6,0,Mapping::linear,0,true,"all",Transition::continuous,10},
    {"reverb.input_trim_db",InputTrim,"Input Trim","dB",-24,12,0,Mapping::linear,0,true,"all",Transition::continuous,10},
    {"reverb.output_trim_db",OutputTrim,"Output Trim","dB",-24,12,0,Mapping::linear,0,true,"all",Transition::continuous,10},
    {"reverb.duck_amount_db",DuckAmount,"Duck Amount","dB",0,24,0,Mapping::linear,0,true,"all",Transition::continuous,10},
    {"reverb.duck_threshold_db",DuckThreshold,"Duck Threshold","dBFS",-60,0,-24,Mapping::linear,0,true,"all",Transition::continuous,10},
    {"reverb.duck_attack_ms",DuckAttack,"Duck Attack","ms",0.5,100,5,Mapping::logarithmic,0,true,"all",Transition::continuous,10},
    {"reverb.duck_release_ms",DuckRelease,"Duck Release","ms",20,2000,200,Mapping::logarithmic,0,true,"all",Transition::continuous,10},
    {"reverb.freeze",Freeze,"Freeze","",0,1,0,Mapping::linear,1,true,"all",Transition::discrete,50},
    {"reverb.predelay_sync",Sync,"Pre-delay Sync","",0,1,0,Mapping::linear,1,true,"all",Transition::discrete,20},
    {"reverb.predelay_division",Division,"Pre-delay Division","",0,11,4,Mapping::linear,11,true,"all",Transition::discrete,20,divisionLabels},
};
inline constexpr ParameterRegistry registry{parameters,std::size(parameters)};
inline double physical(const SoundState& s, ID id) noexcept { const auto i=registry.index(id); return parameters[i].toPhysical(s.targets[i]); }
inline void set(SoundState& s, ID id, double value) noexcept { const auto i=registry.index(id); s.targets[i]=parameters[i].toNormalized(value); }
}
namespace just::module { inline constexpr auto& parameters=reverb::parameters; }
